import React, { useState, useEffect, useRef } from 'react';
import AriaLoader from '../../components/ui/AriaLoader';
import { useOutletContext, useParams, useNavigate } from 'react-router-dom';
import { createPortal } from 'react-dom';
import {
  ArrowRight,
  ArrowLeft,
  Plus,
  X,
  GripVertical,
  ChevronDown,
  Check,
  FolderPlus,
  Info,
  BookOpen,
  Lock,
} from 'lucide-react';
import InterviewPrepService from '../../services/interviewPrep.service';
import { toast } from 'sonner';
import { motion, AnimatePresence } from 'framer-motion';
import { useTranslation, Trans } from 'react-i18next';
import SectionTips from '../../components/SectionTips';
import StepHeader from '../../components/cv/StepHeader';
import JobKeywordPanel from '../../components/cv/JobKeywordPanel';

const Skills = () => {
  const { t } = useTranslation();
  const context = useOutletContext();
  const {
    cvData,
    handleNext,
    handleBack,
    saving,
    user,
    updateCvData,
    setStepDirty,
    registerStepData,
    externalEditNonce,
  } = context || {};
  const { id: draftCVId } = useParams();
  const navigate = useNavigate();

  const isPro = user?.tier && user.tier !== 'free';

  // Migrate legacy string skills → the { name, category, isAutoGenerated } object shape.
  const migrateSkills = (s) =>
    typeof (s || [])[0] === 'string'
      ? s.map((n) => ({ name: n, category: 'Uncategorized', isAutoGenerated: false }))
      : s || [];

  // State — seed once from the draft (skill generation now lives in Aria's chat, which
  // writes via applySkills → externalEditNonce re-seeds; see below).
  const [skillsData, setSkillsData] = useState(() => migrateSkills(cvData?.skills));
  // Index of the skill whose evidence popover is currently open. null = none.
  const [openEvidenceIndex, setOpenEvidenceIndex] = useState(null);
  // Name of the skill whose Pro lock overlay is open. null = none.
  const [openProLockSkill, setOpenProLockSkill] = useState(null);
  // The job keyword awaiting an honesty check before it may go on the CV (see
  // addKeywordAsSkill). Null = no prompt open.
  const [keywordToConfirm, setKeywordToConfirm] = useState(null);
  // Saving the skill+evidence pack to Interview Prep.
  const [savingPrep, setSavingPrep] = useState(false);
  const [prepSaved, setPrepSaved] = useState(false);

  // Manual Entry State
  const [newSkillName, setNewSkillName] = useState('');
  const [newSkillCategory, setNewSkillCategory] = useState('Uncategorized');
  const [availableCategories, setAvailableCategories] = useState(['Uncategorized']);
  // Inline "new category" mode replaces the dropdown with a text input so
  // users can name a category without a separate modal or extra screen.
  const [creatingNewCategory, setCreatingNewCategory] = useState(false);
  const [newCategoryName, setNewCategoryName] = useState('');
  const [categoryDropdownOpen, setCategoryDropdownOpen] = useState(false);
  const categoryDropdownRef = useRef(null);

  // Close the custom category dropdown on outside click or Escape.
  useEffect(() => {
    if (!categoryDropdownOpen) return;
    const handleClick = (e) => {
      if (categoryDropdownRef.current && !categoryDropdownRef.current.contains(e.target)) {
        setCategoryDropdownOpen(false);
      }
    };
    const handleKey = (e) => {
      if (e.key === 'Escape') setCategoryDropdownOpen(false);
    };
    document.addEventListener('mousedown', handleClick);
    document.addEventListener('keydown', handleKey);
    return () => {
      document.removeEventListener('mousedown', handleClick);
      document.removeEventListener('keydown', handleKey);
    };
  }, [categoryDropdownOpen]);

  // Re-seed from the draft ONLY when a coach action writes skills (externalEditNonce
  // bumps — e.g. Aria's in-chat "Find my skills → Add"). Skipping the initial mount
  // (state is already seeded from cvData above) means an ordinary cvData change no
  // longer clobbers in-progress manual edits.
  const seededOnce = useRef(false);
  useEffect(() => {
    if (!seededOnce.current) {
      seededOnce.current = true;
      return;
    }
    setSkillsData(migrateSkills(cvData?.skills));
    // Only react to the nonce — cvData is read fresh on each coach-driven bump.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [externalEditNonce]);

  // Update available categories based on current skills. Default the new-skill
  // category to the most common existing category when one exists — most
  // additions go into a category the user already has.
  useEffect(() => {
    const cats = new Set(['Uncategorized']);
    skillsData.forEach((s) => cats.add(s.category));
    const list = Array.from(cats);
    setAvailableCategories(list);
    // If the currently selected category no longer exists (e.g., last skill in
    // it was deleted), fall back to a valid one.
    if (!list.includes(newSkillCategory)) {
      setNewSkillCategory(list[0] || 'Uncategorized');
    }
  }, [skillsData]);

  // Expose this step's current data so the wizard can flush it when the user
  // jumps to another section via the step navigator.
  useEffect(() => {
    registerStepData?.(() => ({ skills: skillsData }));
    return () => registerStepData?.(null);
  }, [skillsData, registerStepData]);

  // Render guard lives below the hooks so the hook call order is stable
  // across renders (rules-of-hooks).
  if (!cvData) {
    return (
      <div className="p-8 text-center text-slate-500 dark:text-slate-400">
        {t('cvBuilder.skills.loading')}
      </div>
    );
  }

  // AI Generation Handler — opens the review modal instead of auto-merging, so
  // the user picks which skills to add (and free vs paid gating is applied there).
  // Skill generation now lives in Aria's chat ("Find my skills"), which writes to the
  // CV via applySkills — this step just re-seeds off externalEditNonce (above).

  // Manual Add — accepts both button click and Enter key in the skill input.
  const addSkill = (e) => {
    if (e?.preventDefault) e.preventDefault();
    const name = newSkillName.trim();
    if (!name) return;

    // If we're in "create new category" mode, finalize the name first.
    let category = newSkillCategory;
    if (creatingNewCategory) {
      const candidate = newCategoryName.trim();
      if (!candidate) {
        toast.error(t('cvBuilder.skills.giveCategoryName'));
        return;
      }
      category = candidate;
      setCreatingNewCategory(false);
      setNewCategoryName('');
      setNewSkillCategory(candidate);
    }
    if (!category) category = 'Uncategorized';

    // Avoid duplicate names (case-insensitive)
    if (skillsData.some((s) => s.name.toLowerCase() === name.toLowerCase())) {
      toast.error(t('cvBuilder.skills.alreadyInList', { name }));
      return;
    }

    setSkillsData([...skillsData, { name, category, isAutoGenerated: false }]);
    setStepDirty?.(true);
    setNewSkillName('');
  };

  const removeSkill = (indexToRemove) => {
    setStepDirty?.(true);
    setSkillsData(skillsData.filter((_, index) => index !== indexToRemove));
  };

  // Persist the paid AI keyword extraction back into cvData so the wizard's
  // auto-save keeps it (and the backend's charge-once check stays valid).
  const handleKeywordsEnhanced = ({ keywords, aiKeywordsHash }) => {
    updateCvData?.({
      targetJob: { ...cvData.targetJob, aiKeywords: keywords, aiKeywordsHash },
    });
  };

  // Clicking a job keyword used to put it straight on the CV with `evidence: []` — one
  // tap, no questions, a back door around the entire evidence contract that everything
  // else in the skills pipeline enforces. The employer wanting a skill has never been
  // proof that the candidate has it.
  //
  // The affordance stays (it's a useful shortcut when you genuinely forgot to list
  // something); it now asks the same question the confirmation cards ask.
  // `keywordToConfirm` is declared with the other hooks at the top — this component has
  // an early return above, so a hook here would be called conditionally.
  const addKeywordAsSkill = (name) => {
    const clean = (name || '').trim();
    if (!clean) return;
    if (skillsData.some((s) => s.name.toLowerCase() === clean.toLowerCase())) {
      toast.info(t('cvBuilder.skills.alreadyInList', { name: clean }));
      return;
    }
    setKeywordToConfirm(clean);
  };

  // `level` is a rung of the honesty ladder. 'direct'/'basic' put it on the CV with the
  // user's own confirmation recorded as the evidence; 'encountered'/'no' add nothing —
  // "the employer asks for this" is a gap to be honest about, not a skill.
  const confirmKeywordSkill = (level) => {
    const clean = keywordToConfirm;
    setKeywordToConfirm(null);
    if (!clean || !['direct', 'basic'].includes(level)) return;
    setSkillsData((prev) => [
      ...prev,
      {
        name: clean,
        category: 'Uncategorized',
        isAutoGenerated: false,
        explicitlyConfirmed: true,
        confirmationStatus: level,
        evidence: [
          {
            type: 'user_confirmed',
            snippet:
              level === 'direct'
                ? t('cvBuilder.skills.confirmKeyword.evidenceDirect')
                : t('cvBuilder.skills.confirmKeyword.evidenceBasic'),
          },
        ],
      },
    ]);
    setStepDirty?.(true);
    toast.success(t('cvBuilder.skills.added', { name: clean }));
  };

  // Save the AI-generated skills (with evidence + talking points) to the
  // user's Interview Prep. The CV builder doesn't know the applicationId
  // directly, so the backend resolves it from draftCVId by finding linked
  // applications. If none exist, friendly toast tells the user to run a
  // job analysis first.
  const handleSaveToInterviewPrep = async () => {
    if (!draftCVId) {
      toast.error(t('cvBuilder.skills.saveCvFirstPrep'));
      return;
    }
    setSavingPrep(true);
    try {
      // Send the in-memory skills state so the prep reflects what the user
      // currently sees on screen, even if they haven't pressed Next to
      // persist the wizard step yet.
      const payload = skillsData
        .filter((s) => Array.isArray(s.evidence) && s.evidence.length > 0)
        .map((s) => ({
          name: s.name,
          category: s.category,
          evidence: s.evidence,
          talkingPoint: s.talkingPoint,
        }));

      const result = await InterviewPrepService.saveSkillsByDraft(draftCVId, payload);
      setPrepSaved(true);
      // Different success messaging depending on what we attached to.
      if (result.applicationCount > 1) {
        toast.success(t('cvBuilder.skills.savedToApps', { n: result.applicationCount }));
      } else if (result.source === 'application') {
        toast.success(t('cvBuilder.skills.savedToPrep'));
      } else {
        toast.success(t('cvBuilder.skills.savedToPrepAttach'));
      }
      // Stay in the CV builder — the prep is saved in the background and the
      // user can keep building. They'll find it under Interview Prep later.
    } catch (error) {
      const msg = error.response?.data?.message;
      toast.error(msg || t('cvBuilder.skills.couldntSavePrep'));
    } finally {
      setSavingPrep(false);
    }
  };

  const skillsWithEvidenceCount = skillsData.filter(
    (s) => Array.isArray(s.evidence) && s.evidence.length > 0
  ).length;

  const hasAutoGeneratedSkills = skillsData.some((s) => s.isAutoGenerated);
  const showSaveToPrep = isPro ? skillsWithEvidenceCount > 0 : hasAutoGeneratedSkills;

  const onSubmit = (e) => {
    e.preventDefault();
    setStepDirty?.(false);
    handleNext({ skills: skillsData });
  };

  // Group for display
  const groupedSkills = skillsData.reduce((acc, skill) => {
    const cat = skill.category || 'Uncategorized';
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(skill);
    return acc;
  }, {});

  return (
    <form
      onSubmit={onSubmit}
      className="space-y-6 animate-in fade-in slide-in-from-right-8 duration-500"
    >
      <StepHeader
        eyebrow={t('cvBuilder.skills.eyebrow')}
        title={t('cvBuilder.skills.title')}
        subtitle={t('cvBuilder.skills.subtitle')}
      />

      <SectionTips
        sectionKey="cvbuilder_skills"
        title={t('cvBuilder.skills.tips.title')}
        intro={t('cvBuilder.skills.tips.intro')}
        tips={[
          t('cvBuilder.skills.tips.list.0'),
          t('cvBuilder.skills.tips.list.1'),
          t('cvBuilder.skills.tips.list.2'),
          t('cvBuilder.skills.tips.list.3'),
          t('cvBuilder.skills.tips.list.4'),
        ]}
      />

      {/* Skill generation moved into Aria's chat — point users there. */}
      <p className="text-xs text-slate-500 dark:text-slate-400">
        {t('cvBuilder.skills.findSkillsHint')}
      </p>

      <JobKeywordPanel
        floating
        targetJob={cvData?.targetJob}
        coveredSkills={skillsData.map((s) => s.name)}
        draftId={draftCVId}
        onAddKeyword={addKeywordAsSkill}
        onEnhanced={handleKeywordsEnhanced}
      />

      {/* Add Skill — single row: category selector + skill input + Add button.
          Press Enter in the skill input to add, no need to reach for the button.
          "+ New category" inline mode swaps the dropdown for a text input. */}
      <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-200 dark:border-slate-700 space-y-2">
        <div className="flex flex-col sm:flex-row gap-2 items-stretch">
          {/* Category control */}
          {creatingNewCategory ? (
            <div className="sm:w-44 flex items-center gap-1">
              <input
                type="text"
                autoFocus
                value={newCategoryName}
                onChange={(e) => setNewCategoryName(e.target.value)}
                placeholder={t('cvBuilder.skills.categoryName')}
                className="flex-1 p-2.5 border border-slate-300 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200 rounded-lg focus:ring-1 focus:ring-slate-900 dark:focus:ring-white outline-none text-sm"
              />
              <button
                type="button"
                onClick={() => {
                  setCreatingNewCategory(false);
                  setNewCategoryName('');
                }}
                title={t('common.cancel')}
                className="p-2 text-slate-400 dark:text-slate-500 hover:text-slate-700 dark:hover:text-slate-200 rounded-md"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          ) : (
            <div className="sm:w-44 relative" ref={categoryDropdownRef}>
              <button
                type="button"
                onClick={() => setCategoryDropdownOpen((v) => !v)}
                aria-haspopup="listbox"
                aria-expanded={categoryDropdownOpen}
                className={`w-full p-2.5 pr-8 border rounded-lg outline-none text-sm bg-white dark:bg-slate-900 text-left transition-colors flex items-center ${
                  categoryDropdownOpen
                    ? 'border-slate-400 dark:border-slate-500 ring-1 ring-slate-300 dark:ring-slate-600'
                    : 'border-slate-300 dark:border-slate-600 hover:border-slate-400 dark:hover:border-slate-500'
                }`}
              >
                <span className="truncate text-slate-700 dark:text-slate-300">
                  {newSkillCategory === 'Uncategorized'
                    ? t('cvBuilder.skillsCard.uncategorized')
                    : newSkillCategory}
                </span>
              </button>
              <ChevronDown
                className={`w-4 h-4 absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 dark:text-slate-500 pointer-events-none transition-transform ${
                  categoryDropdownOpen ? 'rotate-180' : ''
                }`}
              />

              <AnimatePresence>
                {categoryDropdownOpen && (
                  <motion.div
                    initial={{ opacity: 0, y: -4 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -4 }}
                    transition={{ duration: 0.12 }}
                    role="listbox"
                    className="absolute z-30 left-0 right-0 mt-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg shadow-lg overflow-hidden max-h-64 overflow-y-auto"
                  >
                    {availableCategories.map((cat) => {
                      const selected = cat === newSkillCategory;
                      return (
                        <button
                          key={cat}
                          type="button"
                          role="option"
                          aria-selected={selected}
                          onClick={() => {
                            setNewSkillCategory(cat);
                            setCategoryDropdownOpen(false);
                          }}
                          className={`w-full flex items-center gap-2 px-3 py-2 text-sm text-left transition-colors ${
                            selected
                              ? 'bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-slate-100 font-medium'
                              : 'text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700'
                          }`}
                        >
                          <span className="flex-1 truncate">
                            {cat === 'Uncategorized'
                              ? t('cvBuilder.skillsCard.uncategorized')
                              : cat}
                          </span>
                          {selected && (
                            <Check className="w-3.5 h-3.5 text-slate-500 dark:text-slate-400 shrink-0" />
                          )}
                        </button>
                      );
                    })}
                    {/* Visually-distinct "create new" row at the bottom */}
                    <button
                      type="button"
                      onClick={() => {
                        setCategoryDropdownOpen(false);
                        setCreatingNewCategory(true);
                      }}
                      className="w-full flex items-center gap-2 px-3 py-2 text-sm text-left text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 border-t border-slate-100 dark:border-slate-700 font-medium"
                    >
                      <FolderPlus className="w-3.5 h-3.5 shrink-0" />
                      <span>{t('cvBuilder.skills.newCategory')}</span>
                    </button>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          )}

          {/* Skill input — Enter submits */}
          <input
            type="text"
            value={newSkillName}
            onChange={(e) => setNewSkillName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                e.preventDefault();
                addSkill();
              }
            }}
            placeholder={t('cvBuilder.skills.addSkillPlaceholder')}
            className="flex-1 p-2.5 border border-slate-300 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200 rounded-lg focus:ring-1 focus:ring-slate-900 dark:focus:ring-white outline-none text-sm"
          />

          <button
            type="button"
            onClick={addSkill}
            disabled={!newSkillName.trim()}
            className="btn-primary px-4 py-2.5 gap-1.5 shrink-0 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Plus className="w-4 h-4" />
            {t('cvBuilder.skills.add')}
          </button>
        </div>
        <p className="text-[11px] text-slate-400 dark:text-slate-500 px-1">
          <Trans
            i18nKey="cvBuilder.skills.pressEnter"
            components={{
              kbd: (
                <kbd className="px-1 py-0.5 rounded bg-slate-100 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 text-slate-600 dark:text-slate-300" />
              ),
            }}
          />
        </p>
      </div>

      {/* Skills List */}
      <div className="space-y-6">
        {Object.entries(groupedSkills).length === 0 ? (
          <div className="text-center py-12 text-slate-400 dark:text-slate-500 border-2 border-dashed border-slate-200 dark:border-slate-700 rounded-xl">
            <p>{t('cvBuilder.skills.noSkills')}</p>
          </div>
        ) : (
          Object.entries(groupedSkills).map(([category, skills]) => (
            <div key={category} className="animate-in fade-in slide-in-from-bottom-2">
              <h3 className="font-mono text-[10px] uppercase tracking-[0.14em] text-slate-500 dark:text-slate-400 mb-3 flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-slate-300 dark:bg-slate-600"></span>
                {category === 'Uncategorized' ? t('cvBuilder.skillsCard.uncategorized') : category}
              </h3>
              <div className="flex flex-wrap gap-2">
                {skills.map((skill, index) => {
                  // Calculate global index to remove correctly
                  const globalIndex = skillsData.indexOf(skill);
                  const hasEvidence = Array.isArray(skill.evidence) && skill.evidence.length > 0;
                  const showLock = !isPro && skill.isAutoGenerated;
                  return (
                    <div
                      key={index}
                      className="group flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-sm font-medium transition-all bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:border-slate-300 dark:hover:border-slate-600"
                    >
                      <span className="cursor-default">{skill.name}</span>
                      {(hasEvidence || showLock) && (
                        <button
                          type="button"
                          onClick={() => {
                            if (showLock) {
                              setOpenProLockSkill(skill.name);
                            } else {
                              setOpenEvidenceIndex(globalIndex);
                            }
                          }}
                          aria-label={
                            showLock
                              ? t('cvBuilder.skills.unlockTalkingPoints', { name: skill.name })
                              : t('cvBuilder.skills.whyOnCv', { name: skill.name })
                          }
                          title={
                            showLock
                              ? t('cvBuilder.skills.unlockStar')
                              : t('cvBuilder.skills.whereFrom')
                          }
                          className="p-1.5 -m-1 inline-flex items-center justify-center text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
                        >
                          {showLock ? (
                            <Lock className="w-3 h-3 text-slate-400 dark:text-slate-500" />
                          ) : (
                            <Info className="w-3.5 h-3.5" />
                          )}
                        </button>
                      )}
                      <button
                        type="button"
                        onClick={() => removeSkill(globalIndex)}
                        aria-label={t('cvBuilder.skills.remove', { name: skill.name })}
                        className="p-1.5 -m-1 inline-flex items-center justify-center transition-colors shrink-0 text-slate-400 dark:text-slate-500 hover:text-rose-600 dark:hover:text-rose-400"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  );
                })}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Save-to-Interview-Prep CTA — appears once AI has generated skills with
          evidence. Tells the user explicitly that these skills can be saved
          for interview rehearsal, and that they're the kind of skills an
          interviewer is most likely to ask about. */}
      <AnimatePresence>
        {showSaveToPrep && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
            transition={{ duration: 0.25 }}
            className="rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/40 p-4 sm:p-5"
          >
            <div className="flex items-start gap-3">
              {isPro ? (
                <BookOpen className="w-4 h-4 text-slate-400 dark:text-slate-500 shrink-0 mt-1" />
              ) : (
                <Lock className="w-4 h-4 text-slate-400 dark:text-slate-500 shrink-0 mt-1" />
              )}
              <div className="flex-1 min-w-0">
                <h4 className="font-heading text-sm sm:text-base font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                  <span>{t('cvBuilder.skills.saveToPrep')}</span>
                  {!isPro && (
                    <span className="font-mono text-[10px] uppercase tracking-[0.1em] bg-amber-50 dark:bg-amber-500/15 text-amber-700 dark:text-amber-300 px-1.5 py-0.5 rounded">
                      {t('cvBuilder.skills.proBadge')}
                    </span>
                  )}
                </h4>
                <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 mt-1 leading-relaxed">
                  {isPro
                    ? t('cvBuilder.skills.proBodyPro', { count: skillsWithEvidenceCount })
                    : t('cvBuilder.skills.proBodyFree')}
                </p>
                <div className="mt-3 flex flex-col sm:flex-row gap-2">
                  {isPro ? (
                    <button
                      type="button"
                      onClick={handleSaveToInterviewPrep}
                      disabled={savingPrep || prepSaved}
                      className={
                        prepSaved
                          ? 'inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-semibold bg-emerald-600 text-white cursor-default'
                          : 'btn-primary gap-2 px-4 py-2.5 rounded-lg text-sm disabled:bg-slate-300 disabled:cursor-not-allowed'
                      }
                    >
                      {savingPrep ? (
                        <>
                          <AriaLoader inline tone="mono" size={14} label="" />
                          {t('cvBuilder.common.saving')}
                        </>
                      ) : prepSaved ? (
                        <>
                          <Check className="w-4 h-4" /> {t('cvBuilder.skills.saved')}
                        </>
                      ) : (
                        <>
                          <BookOpen className="w-4 h-4" /> {t('cvBuilder.skills.saveToPrep')}
                        </>
                      )}
                    </button>
                  ) : (
                    <a
                      href="/pricing"
                      className="btn-primary gap-2 px-4 py-2.5 rounded-lg text-sm w-full sm:w-auto"
                    >
                      {t('cvBuilder.skills.upgradeUnlock')}
                    </a>
                  )}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Evidence popover — portaled to body so it floats above the wizard's
          sticky elements without z-index battles. Acts as a centered modal on
          desktop and a bottom sheet on mobile. */}
      {openEvidenceIndex !== null &&
        skillsData[openEvidenceIndex] &&
        typeof document !== 'undefined' &&
        createPortal(
          <AnimatePresence>
            <motion.div
              key="evidence-overlay"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.15 }}
              onClick={() => setOpenEvidenceIndex(null)}
              className="fixed inset-0 z-[200] bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center"
            >
              <motion.div
                key="evidence-card"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 20 }}
                transition={{ duration: 0.2 }}
                onClick={(e) => e.stopPropagation()}
                className="bg-white dark:bg-slate-900 w-full sm:max-w-md sm:m-4 rounded-t-3xl sm:rounded-2xl p-6 max-h-[85vh] overflow-y-auto pb-[max(1.5rem,env(safe-area-inset-bottom))]"
              >
                {/* Drag-handle affordance on mobile */}
                <div className="w-10 h-1 bg-slate-300 dark:bg-slate-600 rounded-full mx-auto mb-4 sm:hidden" />

                <div className="flex items-start justify-between mb-4">
                  <div>
                    <p className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-0.5">
                      {t('cvBuilder.skills.whereComesFrom')}
                    </p>
                    <h3 className="text-xl font-bold text-slate-900 dark:text-slate-100">
                      {skillsData[openEvidenceIndex].name}
                    </h3>
                  </div>
                  <button
                    type="button"
                    onClick={() => setOpenEvidenceIndex(null)}
                    className="p-1.5 rounded-full text-slate-400 dark:text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700 hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
                    aria-label={t('common.close')}
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                {skillsData[openEvidenceIndex].evidence?.length > 0 && (
                  <div className="space-y-3 mb-5">
                    {skillsData[openEvidenceIndex].evidence.map((ev, i) => {
                      const palette =
                        ev.type === 'project'
                          ? 'bg-emerald-50 dark:bg-emerald-500/15 text-emerald-700 dark:text-emerald-300'
                          : ev.type === 'education'
                            ? 'bg-amber-50 dark:bg-amber-500/15 text-amber-700 dark:text-amber-300'
                            : 'bg-slate-100 dark:bg-slate-500/15 text-slate-700 dark:text-slate-300';
                      return (
                        <div key={i} className="flex gap-3">
                          <span
                            className={`shrink-0 inline-flex items-center px-2 py-0.5 rounded-md text-[10px] font-bold uppercase tracking-wider h-fit ${palette}`}
                          >
                            {ev.type}
                          </span>
                          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                            {ev.snippet}
                          </p>
                        </div>
                      );
                    })}
                  </div>
                )}

                {skillsData[openEvidenceIndex].talkingPoint && (
                  <div className="border-t border-slate-100 dark:border-slate-700 pt-4">
                    <div className="flex items-center gap-1.5 mb-2">
                      <BookOpen className="w-4 h-4 text-slate-500 dark:text-slate-400" />
                      <p className="text-xs font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                        {t('cvBuilder.skills.interviewTalkingPoint')}
                      </p>
                    </div>
                    <p className="text-sm italic text-slate-600 dark:text-slate-300 leading-relaxed">
                      "{skillsData[openEvidenceIndex].talkingPoint}"
                    </p>
                  </div>
                )}
              </motion.div>
            </motion.div>
          </AnimatePresence>,
          document.body
        )}

      {/* Pro Lock Modal */}
      {openProLockSkill !== null &&
        typeof document !== 'undefined' &&
        createPortal(
          <AnimatePresence>
            <motion.div
              key="pro-lock-overlay"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.15 }}
              onClick={() => setOpenProLockSkill(null)}
              className="fixed inset-0 z-[200] bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center"
            >
              <motion.div
                key="pro-lock-card"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 20 }}
                transition={{ duration: 0.2 }}
                onClick={(e) => e.stopPropagation()}
                className="bg-white dark:bg-slate-900 w-full sm:max-w-md sm:m-4 rounded-t-2xl sm:rounded-xl p-6 max-h-[85vh] overflow-y-auto pb-[max(1.5rem,env(safe-area-inset-bottom))]"
              >
                {/* Drag-handle affordance on mobile */}
                <div className="w-10 h-1 bg-slate-300 dark:bg-slate-600 rounded-full mx-auto mb-4 sm:hidden" />

                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <div className="p-2 rounded-lg bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400 shrink-0">
                      <Lock className="w-5 h-5" />
                    </div>
                    <div>
                      <p className="text-[10px] font-bold text-amber-600 dark:text-amber-400 uppercase tracking-wider mb-0.5">
                        {t('cvBuilder.skills.proFeature')}
                      </p>
                      <h3 className="font-heading text-lg font-bold text-slate-900 dark:text-slate-100">
                        {t('cvBuilder.skills.talkingPointsTitle')}
                      </h3>
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => setOpenProLockSkill(null)}
                    className="p-1.5 rounded-full text-slate-400 dark:text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700 hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
                    aria-label={t('common.close')}
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                <div className="space-y-4">
                  <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                    <Trans
                      i18nKey="cvBuilder.skills.proLockBody"
                      values={{ name: openProLockSkill }}
                      components={{ b: <strong className="text-slate-800 dark:text-slate-200" /> }}
                    />
                  </p>

                  <div className="bg-slate-50 dark:bg-slate-900/50 rounded-xl p-3.5 border border-slate-100 dark:border-slate-800 relative overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-slate-50 dark:to-slate-900 pointer-events-none" />
                    <div className="flex items-center gap-1.5 mb-2 shrink-0">
                      <BookOpen className="w-3.5 h-3.5 text-slate-400" />
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                        {t('cvBuilder.skills.starPreviewLabel')}
                      </p>
                    </div>
                    <p className="text-xs italic text-slate-400 select-none blur-[2px]">
                      “{t('cvBuilder.skills.starPreviewText')}”
                    </p>
                  </div>

                  <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                    {t('cvBuilder.skills.proAnalyzes')}
                  </p>

                  <div className="pt-2 flex flex-col gap-2">
                    <a
                      href="/upgrade"
                      className="btn-primary text-sm py-3 px-4 rounded-xl gap-2 text-center"
                    >
                      <span>{t('cvBuilder.skills.upgradeToPro')}</span>
                    </a>
                    <button
                      type="button"
                      onClick={() => setOpenProLockSkill(null)}
                      className="text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200 text-xs font-medium py-2 transition-colors"
                    >
                      {t('cvBuilder.skills.maybeLater')}
                    </button>
                  </div>
                </div>
              </motion.div>
            </motion.div>
          </AnimatePresence>,
          document.body
        )}

      {/* The honesty check behind a job-keyword tap. Four rungs, and only the first two
          put anything on the CV — "the employer asks for this" was never proof that the
          candidate has it. */}
      {keywordToConfirm &&
        createPortal(
          <AnimatePresence>
            <motion.div
              key="keyword-confirm-overlay"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.15 }}
              onClick={() => setKeywordToConfirm(null)}
              className="fixed inset-0 z-[200] bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center"
            >
              <motion.div
                key="keyword-confirm-card"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 20 }}
                transition={{ duration: 0.2 }}
                onClick={(e) => e.stopPropagation()}
                className="bg-white dark:bg-slate-900 w-full sm:max-w-md sm:m-4 rounded-t-2xl sm:rounded-xl p-6 max-h-[85vh] overflow-y-auto pb-[max(1.5rem,env(safe-area-inset-bottom))]"
              >
                <div className="w-10 h-1 bg-slate-300 dark:bg-slate-600 rounded-full mx-auto mb-4 sm:hidden" />

                <h3 className="font-heading text-lg font-bold text-slate-900 dark:text-slate-100 mb-1.5">
                  {t('cvBuilder.skills.confirmKeyword.title', { name: keywordToConfirm })}
                </h3>
                <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
                  {t('cvBuilder.skills.confirmKeyword.body')}
                </p>

                <div className="flex flex-col gap-2">
                  {['direct', 'basic', 'encountered', 'no'].map((level) => (
                    <button
                      key={level}
                      type="button"
                      onClick={() => confirmKeywordSkill(level)}
                      className="text-left text-sm font-semibold px-4 py-3 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:border-slate-900 dark:hover:border-white transition-colors"
                    >
                      {t(`cvBuilder.skills.confirmKeyword.levels.${level}`)}
                    </button>
                  ))}
                </div>

                <p className="text-xs text-slate-400 dark:text-slate-500 mt-3">
                  {t('cvBuilder.skills.confirmKeyword.reassure')}
                </p>
              </motion.div>
            </motion.div>
          </AnimatePresence>,
          document.body
        )}

      {/* Navigation */}
      <div className="pt-6 border-t border-slate-100 dark:border-slate-800 flex flex-col-reverse md:flex-row justify-between gap-3 md:gap-0">
        <button
          type="button"
          onClick={handleBack}
          className="w-full md:w-auto px-6 py-3 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 rounded-lg font-medium flex items-center justify-center md:justify-start gap-2 transition-colors border md:border-transparent border-slate-200 dark:border-slate-700"
        >
          <ArrowLeft className="w-4 h-4" /> {t('common.back')}
        </button>
        <button
          type="submit"
          disabled={saving}
          className="w-full md:w-auto btn-primary px-8 py-3 flex items-center justify-center gap-2"
        >
          {saving ? t('cvBuilder.common.saving') : t('cvBuilder.skills.nextSummary')}{' '}
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </form>
  );
};

export default Skills;
