import React, { useState, useEffect } from 'react';
import { useOutletContext } from 'react-router-dom';
import { Cpu, ArrowRight, ArrowLeft, Plus, X, Sparkles, BrainCircuit, GripVertical } from 'lucide-react';
import CVService from '../../services/cv.service';
import UserService from '../../services/user.service';
import { toast } from 'sonner';
import { motion, AnimatePresence } from 'framer-motion';

const Skills = () => {
    const context = useOutletContext();
    const { cvData, handleNext, handleBack, saving, user, updateUser } = context || {};

    if (!cvData) {
        return <div className="p-8 text-center text-slate-500">Loading skills...</div>;
    }

    // State
    const [skillsData, setSkillsData] = useState([]);
    const [loadingAi, setLoadingAi] = useState(false);
    const [showAiBanner, setShowAiBanner] = useState(true);

    // Manual Entry State
    const [newSkillName, setNewSkillName] = useState('');
    const [newSkillCategory, setNewSkillCategory] = useState('');
    const [availableCategories, setAvailableCategories] = useState(['Uncategorized']);

    // Initialize Data
    useEffect(() => {
        if (cvData.skills && cvData.skills.length > 0) {
            // Check if skills are old strings or new objects
            const isOldFormat = typeof cvData.skills[0] === 'string';

            if (isOldFormat) {
                // Migrate on fly for display
                setSkillsData(cvData.skills.map(s => ({ name: s, category: 'Uncategorized', isAutoGenerated: false })));
            } else {
                setSkillsData(cvData.skills);
            }
        } else {
            setSkillsData([]);
        }
    }, [cvData]);

    // Update available categories based on current skills
    useEffect(() => {
        const cats = new Set(['Uncategorized']);
        skillsData.forEach(s => cats.add(s.category));
        setAvailableCategories(Array.from(cats));
    }, [skillsData]);

    // Check User Preference for Banner
    useEffect(() => {
        if (user?.settings?.hideSkillsAiPrompt) {
            setShowAiBanner(false);
        }
    }, [user]);

    // AI Generation Handler
    const handleGenerateSkills = async () => {
        setLoadingAi(true);
        try {
            const result = await CVService.generateSkills(
                cvData.education,
                cvData.experience,
                cvData.projects,
                cvData.targetJob?.description
            );

            if (result.suggestions) {
                // Formatting result into flat array
                const newSkills = [];
                result.suggestions.forEach(catGroup => {
                    catGroup.skills.forEach(skillName => {
                        // Avoid duplicates
                        if (!skillsData.some(existing => existing.name.toLowerCase() === skillName.toLowerCase())) {
                            newSkills.push({
                                name: skillName,
                                category: catGroup.category,
                                isAutoGenerated: true
                            });
                        }
                    });
                });

                setSkillsData([...skillsData, ...newSkills]);
                toast.success(`Generated ${newSkills.length} new skills!`);
                setShowAiBanner(false); // Hide banner after successful use
            }
        } catch (error) {
            console.error(error);
            if (error.response?.data?.code === 'INSUFFICIENT_CREDITS') {
                toast.error("Insufficient credits (Requires 2 Credits)");
            } else {
                toast.error("Failed to generate skills. Please try again.");
            }
        } finally {
            setLoadingAi(false);
        }
    };

    const handleDismissBanner = async (dontShowAgain) => {
        setShowAiBanner(false);
        if (dontShowAgain && user) {
            try {
                const currentSettings = user.settings || {};
                await UserService.updateSettings({ ...currentSettings, hideSkillsAiPrompt: true });
                // Optimistically update local user context if method exists, otherwise it will sync on next load
                if (updateUser) updateUser({ ...user, settings: { ...currentSettings, hideSkillsAiPrompt: true } });
                toast.success("Preference saved.");
            } catch (error) {
                console.error("Failed to save preference", error);
            }
        }
    };

    // Manual Add
    const addSkill = (e) => {
        e.preventDefault();
        if (!newSkillName.trim()) return;

        const category = newSkillCategory.trim() || 'Uncategorized';

        setSkillsData([...skillsData, {
            name: newSkillName.trim(),
            category: category,
            isAutoGenerated: false
        }]);

        setNewSkillName('');
    };

    const removeSkill = (indexToRemove) => {
        setSkillsData(skillsData.filter((_, index) => index !== indexToRemove));
    };

    const onSubmit = (e) => {
        e.preventDefault();
        handleNext({ skills: skillsData });
    };

    // Group for display
    const groupedSkills = skillsData.reduce((acc, skill) => {
        const cat = skill.category || 'Uncategorized';
        if (!acc[cat]) acc[cat] = [];
        acc[cat].push(skill);
        return acc;
    }, {});

    return (
        <form onSubmit={onSubmit} className="space-y-6 animate-in fade-in slide-in-from-right-8 duration-500">
            {/* Header */}
            <div className="flex items-center gap-3 mb-2">
                <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600">
                    <Cpu className="w-5 h-5" />
                </div>
                <div>
                    <h2 className="text-2xl font-bold text-slate-800">Skills</h2>
                    <p className="text-slate-500">Highlight your expertise.</p>
                </div>
            </div>

            {/* AI Banner */}
            <AnimatePresence>
                {showAiBanner && (
                    <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="bg-gradient-to-r from-violet-600 to-indigo-600 rounded-xl p-6 text-white shadow-lg overflow-hidden relative"
                    >
                        <button
                            type="button"
                            onClick={() => handleDismissBanner(false)}
                            className="absolute top-4 right-4 text-white/60 hover:text-white transition-colors"
                        >
                            <X className="w-5 h-5" />
                        </button>

                        <div className="flex items-start gap-4">
                            <div className="p-3 bg-white/20 rounded-lg backdrop-blur-sm">
                                <BrainCircuit className="w-6 h-6 text-yellow-300" />
                            </div>
                            <div className="flex-1">
                                <h3 className="text-lg font-bold mb-1">Let AI Write Your Skills</h3>
                                <p className="text-indigo-100 text-sm mb-4 max-w-md">
                                    We'll analyze your education, experience, and projects to automatically suggest and categorize your top skills.
                                </p>

                                <div className="flex flex-wrap gap-3 items-center">
                                    <button
                                        type="button"
                                        onClick={handleGenerateSkills}
                                        disabled={loadingAi}
                                        className="bg-white text-indigo-600 hover:bg-indigo-50 px-4 py-2 rounded-lg font-semibold text-sm transition-colors flex items-center gap-2 shadow-sm"
                                    >
                                        {loadingAi ? <Sparkles className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                                        {loadingAi ? 'Analyzing Profile...' : 'Generate Skills (2 Credits)'}
                                    </button>

                                    <button
                                        type="button"
                                        onClick={() => handleDismissBanner(true)}
                                        className="text-xs text-indigo-200 hover:text-white underline underline-offset-4 decoration-indigo-300/50"
                                    >
                                        Don't show this again
                                    </button>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Add Skill Form */}
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 flex flex-col md:flex-row gap-3 items-end md:items-center">
                <div className="flex-1 w-full">
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Skill Name</label>
                    <input
                        type="text"
                        value={newSkillName}
                        onChange={(e) => setNewSkillName(e.target.value)}
                        placeholder="e.g. React.js"
                        className="w-full p-2.5 border border-slate-300 rounded-lg focus:ring-1 focus:ring-indigo-500 outline-none"
                    />
                </div>
                <div className="w-full md:w-1/3">
                    <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Category (Optional)</label>
                    <input
                        type="text"
                        value={newSkillCategory}
                        onChange={(e) => setNewSkillCategory(e.target.value)}
                        placeholder="e.g. Frontend"
                        list="category-suggestions"
                        className="w-full p-2.5 border border-slate-300 rounded-lg focus:ring-1 focus:ring-indigo-500 outline-none"
                    />
                    <datalist id="category-suggestions">
                        {availableCategories.map(cat => <option key={cat} value={cat} />)}
                    </datalist>
                </div>
                <button
                    type="button"
                    onClick={addSkill}
                    disabled={!newSkillName.trim()}
                    className="w-full md:w-auto p-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                    <Plus className="w-5 h-5" />
                </button>
            </div>

            {/* Skills List */}
            <div className="space-y-6">
                {Object.entries(groupedSkills).length === 0 ? (
                    <div className="text-center py-12 text-slate-400 border-2 border-dashed border-slate-200 rounded-xl">
                        <p>No skills added yet.</p>
                    </div>
                ) : (
                    Object.entries(groupedSkills).map(([category, skills]) => (
                        <div key={category} className="animate-in fade-in slide-in-from-bottom-2">
                            <h3 className="text-sm font-bold text-slate-700 uppercase mb-3 flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-indigo-400"></span>
                                {category}
                            </h3>
                            <div className="flex flex-wrap gap-2">
                                {skills.map((skill, index) => {
                                    // Calculate global index to remove correctly
                                    const globalIndex = skillsData.indexOf(skill);
                                    return (
                                        <div
                                            key={index}
                                            className={`
                                                group flex items-center gap-2 px-3 py-1.5 rounded-lg border text-sm font-medium transition-all
                                                ${skill.isAutoGenerated
                                                    ? 'bg-indigo-50 border-indigo-100 text-indigo-700'
                                                    : 'bg-white border-slate-200 text-slate-700 hover:border-slate-300'}
                                            `}
                                        >
                                            <span className="cursor-default">{skill.name}</span>
                                            <button
                                                type="button"
                                                onClick={() => removeSkill(globalIndex)}
                                                className="text-slate-400 hover:text-rose-500 transition-colors opacity-0 group-hover:opacity-100 focus:opacity-100"
                                            >
                                                <X className="w-3 h-3" />
                                            </button>
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    ))
                )}
            </div>

            {/* Navigation */}
            <div className="pt-6 border-t border-slate-100 flex flex-col-reverse md:flex-row justify-between gap-3 md:gap-0">
                <button
                    type="button"
                    onClick={handleBack}
                    className="w-full md:w-auto px-6 py-3 text-slate-600 hover:bg-slate-50 rounded-lg font-medium flex items-center justify-center md:justify-start gap-2 transition-colors border md:border-transparent border-slate-200"
                >
                    <ArrowLeft className="w-4 h-4" /> Back
                </button>
                <button
                    type="submit"
                    disabled={saving}
                    className="w-full md:w-auto btn-primary px-8 py-3 flex items-center justify-center gap-2"
                >
                    {saving ? 'Saving...' : 'Next: Summary'} <ArrowRight className="w-4 h-4" />
                </button>
            </div>
        </form>
    );
};

export default Skills;
