import React, { useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, Check, Lock, X, Info, Target, Crown } from 'lucide-react';
import { toast } from 'sonner';

// Free users can ADD up to this many generated skills. The full set is generated
// for everyone (so the value is visible); the cap is on how many you take. 15 is
// the top of the "aim for 15-25" guidance, so a free user still walks away with a
// complete skills section — the paywall sits on curation, not basic usability.
const FREE_PICK_MAX = 15;

const lower = (s) => (s || '').trim().toLowerCase();

/**
 * Review modal shown after "Auto-fill" generates skills. The whole generated set
 * is presented grouped by category; the user picks which to add (instead of the
 * old auto-dump). Monetization layers:
 *  - Free: add up to 15; the "Best for this role" mode + the ✨/ⓘ "why this wins
 *    this job" intelligence are locked.
 *  - Paid: pick freely; one-click "Best for this role" selects the JD-matched set;
 *    ✨ marks are live and ⓘ reveals the evidence + interview talking point.
 *
 * "Best for this role" is a deterministic JD match computed on the backend
 * (bestForRole = skill names), so it only lights up when a target job exists.
 *
 * @param {object[]} suggestions  [{ category, skills:[], skillsDetailed?:[] }]
 * @param {string[]} bestForRole  Generated skill names that match the target job.
 * @param {boolean}  isPaid
 * @param {string[]} existingSkills  Names already on the CV (shown as added).
 * @param {boolean}  hasJD  A target-job description exists (enables Best-for-role).
 * @param {(skills: object[]) => void} onAdd
 * @param {() => void} onClose
 * @param {() => void} onUpgrade
 */
const GeneratedSkillsModal = ({
  suggestions = [],
  bestForRole = [],
  isPaid = false,
  existingSkills = [],
  hasJD = false,
  onAdd,
  onClose,
  onUpgrade,
}) => {
  const [mode, setMode] = useState('all'); // 'all' | 'best'
  const [selected, setSelected] = useState([]); // skill names
  const [openDetail, setOpenDetail] = useState(null); // skill name with detail expanded

  const existingSet = useMemo(() => new Set(existingSkills.map(lower)), [existingSkills]);
  const bestSet = useMemo(() => new Set(bestForRole.map(lower)), [bestForRole]);

  // Flatten suggestions → display rows, merging per-skill detail (paid) and the
  // deterministic best-for-role flag. Skip skills already on the CV from the count
  // but still show them as "added" so the user sees the full picture.
  const rows = useMemo(() => {
    const out = [];
    const seen = new Set();
    suggestions.forEach((group) => {
      const detailByName = (group.skillsDetailed || []).reduce((acc, d) => {
        if (d?.name) acc[lower(d.name)] = d;
        return acc;
      }, {});
      (group.skills || []).forEach((name) => {
        const key = lower(name);
        if (seen.has(key)) return;
        seen.add(key);
        out.push({
          name,
          category: group.category || 'Uncategorized',
          isBest: bestSet.has(key),
          isAdded: existingSet.has(key),
          detail: detailByName[key] || null,
        });
      });
    });
    return out;
  }, [suggestions, bestSet, existingSet]);

  const selectableCount = rows.filter((r) => !r.isAdded).length;
  const atCap = !isPaid && selected.length >= FREE_PICK_MAX;

  const toggle = (row) => {
    if (row.isAdded) return;
    const key = row.name;
    if (selected.includes(key)) {
      setSelected(selected.filter((n) => n !== key));
      return;
    }
    if (!isPaid && selected.length >= FREE_PICK_MAX) {
      toast.info(`Free plan adds up to ${FREE_PICK_MAX} skills. Upgrade to add the full set.`);
      return;
    }
    setSelected([...selected, key]);
  };

  // Paid one-click: switch to Best mode and pre-select the JD-matched set.
  const enterBestMode = () => {
    if (!hasJD) return;
    if (!isPaid) {
      setMode('best');
      return; // free → renders the locked upsell panel
    }
    setMode('best');
    const bestNames = rows.filter((r) => r.isBest && !r.isAdded).map((r) => r.name);
    setSelected(bestNames);
  };

  const handleAdd = () => {
    if (selected.length === 0) {
      toast.info('Pick at least one skill to add.');
      return;
    }
    const picked = rows
      .filter((r) => selected.includes(r.name))
      .map((r) => ({
        name: r.name,
        category: r.category,
        isAutoGenerated: true,
        // Carry the evidence + talking point for paid users (used by the CV chip
        // ⓘ popover and Save-to-Interview-Prep). Free users have no detail.
        evidence: isPaid && r.detail?.evidence ? r.detail.evidence : [],
        talkingPoint: isPaid && r.detail?.talkingPoint ? r.detail.talkingPoint : '',
      }));
    onAdd?.(picked);
  };

  const grouped = useMemo(() => {
    const g = {};
    rows.forEach((r) => {
      (g[r.category] = g[r.category] || []).push(r);
    });
    return g;
  }, [rows]);

  const bestRows = rows.filter((r) => r.isBest);

  return createPortal(
    <AnimatePresence>
      <motion.div
        key="genskills-overlay"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.15 }}
        onClick={onClose}
        className="fixed inset-0 z-[200] bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-4"
      >
        <motion.div
          key="genskills-card"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 20 }}
          transition={{ duration: 0.2 }}
          onClick={(e) => e.stopPropagation()}
          className="bg-white dark:bg-slate-900 w-full sm:max-w-2xl rounded-t-3xl sm:rounded-2xl flex flex-col max-h-[90dvh] overflow-hidden"
        >
          {/* Header */}
          <div className="p-4 sm:p-5 border-b border-slate-100 dark:border-slate-700 shrink-0">
            <div className="flex items-start justify-between gap-3">
              <div className="flex items-center gap-2.5 min-w-0">
                <div className="w-8 h-8 rounded-lg bg-indigo-100 dark:bg-indigo-500/15 text-indigo-600 dark:text-indigo-300 flex items-center justify-center shrink-0">
                  <Sparkles className="w-4 h-4" />
                </div>
                <div className="min-w-0">
                  <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
                    {selectableCount} skills found
                  </h3>
                  <p className="text-xs text-slate-500 dark:text-slate-400 leading-snug">
                    Pick the ones that are genuinely true for you.
                  </p>
                </div>
              </div>
              <button
                type="button"
                onClick={onClose}
                aria-label="Close"
                className="p-1.5 rounded-full text-slate-400 dark:text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors shrink-0"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Segmented control: All skills | Best for this role */}
            <div className="mt-4 inline-flex p-1 rounded-xl bg-slate-100 dark:bg-slate-800 w-full sm:w-auto">
              <button
                type="button"
                onClick={() => setMode('all')}
                className={`flex-1 sm:flex-none px-4 py-1.5 text-xs font-semibold rounded-lg transition-colors ${
                  mode === 'all'
                    ? 'bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 shadow-sm'
                    : 'text-slate-500 dark:text-slate-400'
                }`}
              >
                All skills
              </button>
              <button
                type="button"
                onClick={enterBestMode}
                disabled={!hasJD}
                title={!hasJD ? 'Add a target job to see which skills win this role' : undefined}
                className={`flex-1 sm:flex-none px-4 py-1.5 text-xs font-semibold rounded-lg transition-colors inline-flex items-center justify-center gap-1.5 disabled:opacity-50 disabled:cursor-not-allowed ${
                  mode === 'best'
                    ? 'bg-white dark:bg-slate-900 text-indigo-700 dark:text-indigo-300 shadow-sm'
                    : 'text-slate-500 dark:text-slate-400'
                }`}
              >
                <Sparkles className="w-3 h-3" />
                Best for this role
                {!isPaid && <Lock className="w-3 h-3" />}
              </button>
            </div>
            {!hasJD && (
              <p className="mt-2 text-[11px] text-slate-400 dark:text-slate-500">
                Add a target job (step 1) to unlock best-fit picks for the role.
              </p>
            )}
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto p-4 sm:p-5 bg-slate-50 dark:bg-slate-950/30">
            {mode === 'best' && !isPaid ? (
              // ── Locked upsell panel (free clicked Best-for-role) ──
              <div className="text-center py-8 px-4">
                <div className="w-12 h-12 mx-auto rounded-xl bg-indigo-100 dark:bg-indigo-500/15 text-indigo-600 dark:text-indigo-300 flex items-center justify-center mb-3">
                  <Target className="w-6 h-6" />
                </div>
                <h4 className="text-base font-bold text-slate-900 dark:text-slate-100">
                  Which skills actually win this job?
                </h4>
                <p className="text-sm text-slate-500 dark:text-slate-400 mt-1.5 max-w-sm mx-auto leading-relaxed">
                  Pro matches your generated skills against the job description and marks the{' '}
                  <strong className="text-slate-700 dark:text-slate-300">
                    {bestRows.length || 'top'}
                  </strong>{' '}
                  that recruiters and ATS screen for — so you lead with the ones that count.
                </p>
                <button
                  type="button"
                  onClick={onUpgrade}
                  className="mt-4 inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold transition-colors shadow-sm"
                >
                  <Crown className="w-4 h-4" /> Upgrade to unlock
                </button>
                <button
                  type="button"
                  onClick={() => setMode('all')}
                  className="block mx-auto mt-3 text-xs font-medium text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200"
                >
                  Back to all skills
                </button>
              </div>
            ) : (
              // ── Skills list (All, or Best for paid) ──
              <div className="space-y-5">
                {(mode === 'best'
                  ? [['Best for this role', bestRows]]
                  : Object.entries(grouped)
                ).map(([category, items]) => (
                  <div key={category}>
                    <h4 className="text-[11px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2 flex items-center gap-1.5">
                      {mode === 'best' && <Sparkles className="w-3 h-3 text-indigo-500" />}
                      {category}
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {items.map((row) => {
                        const isSel = selected.includes(row.name);
                        return (
                          <div
                            key={row.name}
                            className={`group inline-flex items-center gap-1.5 pl-2.5 pr-2 py-1.5 min-h-[40px] rounded-lg border text-sm font-medium transition-all ${
                              row.isAdded
                                ? 'border-slate-200 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-500'
                                : isSel
                                  ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-500/20 text-indigo-700 dark:text-indigo-200'
                                  : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:border-indigo-300 dark:hover:border-indigo-500/40'
                            } ${atCap && !isSel && !row.isAdded ? 'opacity-50' : ''}`}
                          >
                            <button
                              type="button"
                              onClick={() => toggle(row)}
                              disabled={row.isAdded}
                              className="inline-flex items-center gap-1.5 disabled:cursor-default"
                            >
                              <span
                                className={`w-4 h-4 rounded border flex items-center justify-center shrink-0 ${
                                  row.isAdded || isSel
                                    ? 'bg-indigo-500 border-indigo-500 text-white'
                                    : 'border-slate-300 dark:border-slate-600'
                                }`}
                              >
                                {(row.isAdded || isSel) && <Check className="w-3 h-3" />}
                              </span>
                              {row.name}
                            </button>

                            {/* Best-for-role marker. Live for paid; blurred teaser for free. */}
                            {row.isBest &&
                              (isPaid ? (
                                <button
                                  type="button"
                                  onClick={() =>
                                    setOpenDetail(openDetail === row.name ? null : row.name)
                                  }
                                  title="Why this skill wins this job"
                                  className="text-indigo-500 hover:text-indigo-700 dark:hover:text-indigo-300"
                                >
                                  <Info className="w-3.5 h-3.5" />
                                </button>
                              ) : (
                                <button
                                  type="button"
                                  title="Best for this job — upgrade to see why"
                                  onClick={onUpgrade}
                                  className="inline-flex items-center cursor-pointer"
                                >
                                  <Sparkles className="w-3.5 h-3.5 text-indigo-400 blur-[1.5px]" />
                                </button>
                              ))}

                            {row.isAdded && (
                              <span className="text-[10px] uppercase tracking-wide font-bold text-slate-400 dark:text-slate-500">
                                added
                              </span>
                            )}
                          </div>
                        );
                      })}
                    </div>

                    {/* Paid ⓘ detail (evidence + talking point) for the open skill. */}
                    {isPaid &&
                      openDetail &&
                      items.some((r) => r.name === openDetail && r.detail) && (
                        <div className="mt-2 rounded-lg border border-indigo-100 dark:border-indigo-500/30 bg-indigo-50/50 dark:bg-indigo-500/10 p-3 text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                          {(() => {
                            const d = items.find((r) => r.name === openDetail)?.detail;
                            if (!d) return null;
                            return (
                              <>
                                {d.talkingPoint && <p className="italic">"{d.talkingPoint}"</p>}
                                {Array.isArray(d.evidence) && d.evidence.length > 0 && (
                                  <p className="mt-1.5 text-slate-500 dark:text-slate-400">
                                    From your {d.evidence.map((e) => e.type).join(', ')}.
                                  </p>
                                )}
                              </>
                            );
                          })()}
                        </div>
                      )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="p-4 border-t border-slate-100 dark:border-slate-700 bg-white dark:bg-slate-900 shrink-0 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="text-xs font-medium text-slate-500 dark:text-slate-400 min-w-0 truncate">
              {isPaid ? (
                <span>{selected.length} selected</span>
              ) : (
                <span>
                  Picked{' '}
                  <span className="text-slate-800 dark:text-slate-200 font-bold">
                    {selected.length}
                  </span>{' '}
                  / {FREE_PICK_MAX}
                  {atCap && (
                    <span className="text-indigo-600 dark:text-indigo-300">
                      {' '}
                      · upgrade for the full set
                    </span>
                  )}
                </span>
              )}
            </div>
            <div className="flex items-center gap-2 shrink-0">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleAdd}
                disabled={selected.length === 0}
                className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-semibold rounded-lg disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                Add {selected.length > 0 ? selected.length : ''} to CV
              </button>
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>,
    document.body
  );
};

export default GeneratedSkillsModal;
