import React, { useMemo, useState } from 'react';
import { Check, Info } from 'lucide-react';
import { useTranslation } from 'react-i18next';

const lower = (s) => (s || '').trim().toLowerCase();

// Grouped skills picker rendered INLINE in Aria's chat (adapted from the old
// GeneratedSkillsModal, minus the modal shell + the free-pick cap + the locked
// Best-for-role upsell — best-for-role is now a free view for everyone). Purely
// presentational: the parent owns generation, charging, and the durable record.
//
// Props:
//  - suggestions:   [{ category, skills:[], skillsDetailed?:[] }]
//  - bestForRole:   string[] of skill names matching the target job (empty → no JD)
//  - existingSkills:string[] names already on the CV (shown greyed, "on CV", not pickable)
//  - initialSelected: string[] names to pre-check (only for a re-opened record)
//  - onAdd:         (picked: object[]) => void
const SkillsCard = ({
  suggestions = [],
  bestForRole = [],
  existingSkills = [],
  initialSelected = [],
  onAdd,
}) => {
  const { t } = useTranslation();
  const [mode, setMode] = useState('all'); // 'all' | 'role'
  const [selected, setSelected] = useState(() => new Set(initialSelected));
  const [openDetail, setOpenDetail] = useState(null);
  // 'Uncategorized' stays the internal/stored category value; only its display
  // is localized (like the CV section labels — translate at the render layer).
  const catLabel = (c) => (c === 'Uncategorized' ? t('cvBuilder.skillsCard.uncategorized') : c);

  const existingSet = useMemo(() => new Set(existingSkills.map(lower)), [existingSkills]);
  const bestSet = useMemo(() => new Set(bestForRole.map(lower)), [bestForRole]);
  const hasBest = bestForRole.length > 0;

  // Flatten suggestions → display rows, merging per-skill detail + the deterministic
  // best-for-role flag + whether it's already on the CV.
  const rows = useMemo(() => {
    const out = [];
    const seen = new Set();
    suggestions.forEach((group) => {
      const detailByName = (group.skillsDetailed || []).reduce((acc, d) => {
        if (d?.name) acc[lower(d.name)] = d;
        return acc;
      }, {});
      (group.skills || []).forEach((name) => {
        const key = lower(name);
        if (seen.has(key)) return;
        seen.add(key);
        out.push({
          name,
          category: group.category || 'Uncategorized',
          isBest: bestSet.has(key),
          isAdded: existingSet.has(key),
          detail: detailByName[key] || null,
        });
      });
    });
    return out;
  }, [suggestions, bestSet, existingSet]);

  const toggle = (row) => {
    if (row.isAdded) return;
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(row.name)) next.delete(row.name);
      else next.add(row.name);
      return next;
    });
  };

  const handleAdd = () => {
    const picked = rows
      .filter((r) => selected.has(r.name) && !r.isAdded)
      .map((r) => ({
        name: r.name,
        category: r.category,
        isAutoGenerated: true,
        evidence: r.detail?.evidence || [],
        talkingPoint: r.detail?.talkingPoint || '',
      }));
    onAdd?.(picked);
  };

  const grouped = useMemo(() => {
    const g = {};
    rows.forEach((r) => {
      (g[r.category] = g[r.category] || []).push(r);
    });
    return g;
  }, [rows]);

  const bestRows = rows.filter((r) => r.isBest);
  const selectedCount = [...selected].filter((n) => !existingSet.has(lower(n))).length;

  const sections =
    mode === 'role'
      ? [[t('cvBuilder.skillsCard.bestForRole'), bestRows]]
      : Object.entries(grouped);

  return (
    <div className="rounded-2xl border border-slate-200 dark:border-slate-800 border-l-2 border-l-indigo-400 dark:border-l-indigo-500 bg-white dark:bg-slate-900/60 overflow-hidden">
      {/* Header + segmented control. */}
      <div className="p-3.5 border-b border-slate-100 dark:border-slate-800">
        <span className="font-mono text-[10px] uppercase tracking-wide text-indigo-600 dark:text-indigo-300">
          {t('cvBuilder.skillsCard.eyebrow')}
        </span>
        <p className="mt-0.5 text-[12px] text-slate-500 dark:text-slate-400 leading-snug">
          {t('cvBuilder.skillsCard.subtitle')}
        </p>
        <div className="mt-2.5 inline-flex gap-1 p-1 rounded-xl border border-slate-200 dark:border-slate-700">
          <button
            type="button"
            onClick={() => setMode('all')}
            className={`px-3.5 py-1 text-[11px] font-semibold rounded-lg transition-colors ${
              mode === 'all'
                ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900'
                : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
            }`}
          >
            {t('cvBuilder.skillsCard.allSkills')}
          </button>
          <button
            type="button"
            onClick={() => hasBest && setMode('role')}
            disabled={!hasBest}
            title={!hasBest ? t('cvBuilder.skillsCard.addTargetJobTitle') : undefined}
            className={`px-3.5 py-1 text-[11px] font-semibold rounded-lg transition-colors inline-flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed ${
              mode === 'role'
                ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900'
                : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
            }`}
          >
            ★ {t('cvBuilder.skillsCard.bestForRole')}
          </button>
        </div>
        {!hasBest && (
          <p className="mt-1.5 text-[10px] text-slate-400 dark:text-slate-500">
            {t('cvBuilder.skillsCard.addTargetJobHint')}
          </p>
        )}
      </div>

      {/* Grouped chips. */}
      <div className="max-h-[46vh] overflow-y-auto scrollbar-none p-3.5 flex flex-col gap-4 bg-slate-50/60 dark:bg-slate-950/20">
        {sections.map(([category, items]) => (
          <div key={category}>
            <h4 className="text-[10px] font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1.5">
              {catLabel(category)}
            </h4>
            <div className="flex flex-wrap gap-1.5">
              {items.map((row) => {
                const isSel = selected.has(row.name);
                return (
                  <div
                    key={row.name}
                    className={`inline-flex items-center gap-1.5 pl-2.5 pr-2 py-1 rounded-lg border text-[12.5px] font-medium transition-all ${
                      row.isAdded
                        ? 'border-slate-200 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-500'
                        : isSel
                          ? 'border-transparent bg-indigo-50 dark:bg-indigo-500/15 text-indigo-700 dark:text-indigo-300'
                          : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 hover:border-slate-300 dark:hover:border-slate-600'
                    }`}
                  >
                    <button
                      type="button"
                      onClick={() => toggle(row)}
                      disabled={row.isAdded}
                      className="inline-flex items-center gap-1.5 disabled:cursor-default"
                    >
                      <span
                        className={`w-3.5 h-3.5 rounded border flex items-center justify-center shrink-0 ${
                          row.isAdded || isSel
                            ? 'bg-indigo-500 border-indigo-500 text-white'
                            : 'border-slate-300 dark:border-slate-600'
                        }`}
                      >
                        {(row.isAdded || isSel) && <Check className="w-2.5 h-2.5" />}
                      </span>
                      {row.isBest && <span className="text-indigo-500">★</span>}
                      {row.name}
                    </button>

                    {row.detail && (
                      <button
                        type="button"
                        onClick={() => setOpenDetail(openDetail === row.name ? null : row.name)}
                        title={t('cvBuilder.skillsCard.whyFits')}
                        className="text-indigo-500 hover:text-indigo-700 dark:hover:text-indigo-300"
                      >
                        <Info className="w-3 h-3" />
                      </button>
                    )}

                    {row.isAdded && (
                      <span className="text-[9px] uppercase tracking-wide font-bold text-slate-400 dark:text-slate-500">
                        {t('cvBuilder.skillsCard.onCv')}
                      </span>
                    )}
                  </div>
                );
              })}
            </div>

            {openDetail &&
              items.some((r) => r.name === openDetail && r.detail) &&
              (() => {
                const d = items.find((r) => r.name === openDetail)?.detail;
                if (!d) return null;
                return (
                  <div className="mt-2 rounded-lg border border-indigo-100 dark:border-indigo-500/30 bg-indigo-50/50 dark:bg-indigo-500/10 p-2.5 text-[11.5px] text-slate-600 dark:text-slate-300 leading-relaxed">
                    {d.talkingPoint && <p className="italic">"{d.talkingPoint}"</p>}
                    {Array.isArray(d.evidence) && d.evidence.length > 0 && (
                      <p className="mt-1 text-slate-500 dark:text-slate-400">
                        {t('cvBuilder.skillsCard.fromYour', {
                          types: d.evidence.map((e) => e.type).join(', '),
                        })}
                      </p>
                    )}
                  </div>
                );
              })()}
          </div>
        ))}

        {/* Soft-skills steer — set expectations before they hunt for "leadership". */}
        <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed italic border-t border-slate-100 dark:border-slate-800 pt-2.5">
          {t('cvBuilder.skillsCard.softSkillsNote')}
        </p>
      </div>

      {/* Footer. */}
      <div className="p-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between gap-2">
        <span className="text-[11px] font-medium text-slate-500 dark:text-slate-400">
          {t('cvBuilder.skillsCard.selectedCount', { n: selectedCount })}
        </span>
        <button
          type="button"
          onClick={handleAdd}
          disabled={selectedCount === 0}
          className="text-xs font-semibold px-4 py-1.5 rounded-full bg-slate-900 text-white dark:bg-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
        >
          {selectedCount > 0
            ? t('cvBuilder.skillsCard.addNToCv', { n: selectedCount })
            : t('cvBuilder.skillsCard.addToCv')}
        </button>
      </div>
    </div>
  );
};

export default SkillsCard;
